version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11  # Użyj odpowiedniego obrazu z Javą
    working_directory: ~/project

jobs:
  test:
    executor: java-executor
    steps:
      - checkout  # Pobranie kodu z repozytorium
      - run:
          name: Download Dependencies
          command: mvn dependency:resolve  # Pobranie zależności
      - run:
          name: Compile Code
          command: mvn compile  # Kompilacja kodu
      - run:
          name: Run Tests
          command: mvn test  # Uruchomienie testów jednostkowych

workflows:
  version: 2
  test:
    jobs:
      - test
