version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Maven
          command: sudo apt-get install --reinstall ca-certificates-java
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
