# .circleci/config.yml
version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11  # Użyj obrazu z odpowiednią wersją Javy, np. OpenJDK 11
    working_directory: ~/project

jobs:
  test:
    executor: java-executor
    steps:
      - checkout  # Pobranie kodu z repozytorium
      - run:
          name: Download Dependencies
          command: ./mvnw dependency:resolve  # Pobranie zależności (jeśli używasz Maven Wrapper)
      - run:
          name: Compile Code
          command: ./mvnw compile  # Kompilacja kodu
      - run:
          name: Run Tests
          command: ./mvnw test  # Uruchomienie testów jednostkowych

workflows:
  version: 2
  test:
    jobs:
      - test
