version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pytest
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir -p test-results
            PYTHONPATH=. pytest test_calculator.py --junitxml=test-results/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
